'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

Input Format:
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

Constraints:
1 <= T <=10**5
10 <= N <= 4 * 10**16

Sample Input 0
2
10
100

Sample Output 0
10
44
'''
import sys


t = int(input().strip())
for a0 in range(t):
    # n is the limit
    n = int(input().strip())

    f1 = 1
    f2 = 2
    if n == 1:
        print(0)
    elif n == 2:
        print(2)

    fib_list = [f1, f2]
    while f2 < n:
        f1, f2 = f2, f1+f2
        fib_list.append(f2)
    print(sum([i for i in fib_list[:len(fib_list)-1] if i%2==0]))